gui:
  nerdFontsVersion: 3
git:
  pagers:
    - pager: delta --paging=never
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  overrideGpg: true
os:
  # Use the parent Neovim process when available; otherwise start nvim.
  editPreset: nvim-remote
