# True color.
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
# Status bar.
set -g status-justify centre
set-option -g status-position top
# Reload source file.
bind r source-file ~/.tmux.conf \; display "Reloaded!"
# Change prefix key.
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# Split panes using | and -.
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v
# Vim like pane navigation.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Vi mode.
set-window-option -g mode-keys vi
unbind-key -T copy-mode-vi Space
bind-key -T copy-mode-vi v send-keys -X begin-selection
unbind-key -T copy-mode-vi Enter
# TODO Use win32yank.
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel"
unbind-key -T copy-mode-vi C-v
bind-key -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
# Enable mouse.
setw -g mouse on
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \;                 send-keys -M
# Load color scheme.
if-shell "test -f ~/.tmuxline" "source ~/.tmuxline"
