# for Windows

# video output driver
vo=gpu


# graphics API
gpu-api=vulkan


# frame buffer object format
fbo-format=rgba32f


# SVP
input-ipc-server=mpvpipe
# Hardware decoding is discouraged.
# hwdec=auto-copy
# hwdec-codecs=all
hwdec=no
hr-seek-framedrop=no
no-resume-playback


profile=gpu-hq
#     [gpu-hq]
#     scale=spline36
#     cscale=spline36
#     dscale=mitchell
#     dither-depth=auto
#     correct-downscaling=yes
#     linear-downscaling=yes
#     sigmoid-upsaling=yes
#     deband=yes


# chroma upsaling/downscaling
# https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637
# Overwrite the gpu-hq profile.
cscale=bilinear
glsl-shaders-append="~~/KrigBilateral.glsl"


# luma upsaling
# https://github.com/igv/FSRCNN-TensorFlow/releases
# Overwrite the gpu-hq profile.
scale=ewa_lanczossharp
glsl-shaders-append="~~/FSRCNNX_x2_8-0-4-1.glsl"


# interpolation
# https://github.com/mpv-player/mpv/issues/2685
video-sync=display-resample
interpolation=yes
tscale=box
tscale-window=sphinx
tscale-radius=1.01
tscale-clamp=0.0


# debanding
deband-iterations=4


# dithering
dither-size-fruit=7
temporal-dither


# full range
video-output-levels=full


# ICC display profile
icc-profile-auto


# Wasapi
# audio-exclusive


# Misc
volume-max=100
# Hide subtitles.
no-sub-visibility
# Make the window always on top.
ontop
