# Start a non-login shell.
set -g default-command "${SHELL}"

# Reload source file.
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Change prefix key.
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes using | and -.
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# Vim like pane navigation.
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resize pane.
bind -n M-left  resize-pane -L 2
bind -n M-down  resize-pane -D 2
bind -n M-up    resize-pane -U 2
bind -n M-right resize-pane -R 2

# Enable mouse scrolling.
setw -g mouse on
bind-key -T edit-mode-vi Up send-keys -X history-up
bind-key -T edit-mode-vi Down send-keys -X history-down

# Escape response.
set -g escape-time 10

# Color scheme.
# True color.
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# Basic
# Use normal black instead of bright black.
set -g status-style "none, bg=#100e23"
# Left
set -g status-left-length 200
set -g status-left "#[fg=colour13,bg=#100e23]#(whoami) #[fg=colour5,bg=#100e23]#H #[fg=colour2,bg=#100e23]#S"
# Right
set -g status-right ""
# Status
set -g status-position top
set -g status-justify left
setw -g window-status-format "#[fg=#767676,bg=#100e23] #I:#W"
setw -g window-status-current-format "#[fg=colour5,bg=#100e23] #I:#W"
setw -g window-status-separator ""
# Pane
set -g pane-active-border-style "fg=colour5,none"
set -g display-panes-active-colour colour5
set -g pane-border-style "fg=#767676,none"
set -g display-panes-colour "#767676"
set -g display-panes-time 10000
# Clock
unbind t
# Message
set -g message-style "fg=colour1,bg=#100e23"
set -g message-command-style "fg=colour1,bg=#100e23"
# Vi mode
setw -g mode-keys vi
set -g mode-style "fg=colour0, bg=colour3"
