# Video output driver
# https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU
# vo=gpu-next
vo=gpu
 
# Graphics API
gpu-api=vulkan
 
# SVP
# https://www.svp-team.com/wiki/SVP:mpv
input-ipc-server=mpvpipe
hwdec=auto-copy
hwdec-codecs=all
hr-seek-framedrop=no
no-resume-playback
  
profile=gpu-hq
# [gpu-hq]
# scale=spline36
# cscale=spline36
# dscale=mitchell
# dither-depth=auto
# correct-downscaling=yes
# linear-downscaling=yes
# sigmoid-upsaling=yes
# deband=yes

# Overwrite the gpu-hq profile.
# https://wiki.archlinux.org/title/mpv
# scale=ewa_lanczossharp
# cscale=ewa_lanczossharp
video-sync=display-resample
# interpolation  # Leave interpolation to SVP.
# tscale=oversample
 
# Chroma upsaling/downscaling
# https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637
glsl-shaders-append="~~/KrigBilateral.glsl"
 
# Luma upsaling
# https://github.com/igv/FSRCNN-TensorFlow/releases
# glsl-shaders-append="~~/FSRCNNX_x2_8-0-4-1.glsl"
 
# Wasapi
# audio-exclusive
 
volume-max=100
no-sub-visibility # Hide subtitles.
ontop # Make the window always on top.
